MVC5_Full_Version/Inspinia_MVC5/Controllers/JsonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inspinia_MVC5.Controllers
{
    public class JsonController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult flotJsonData()
        {

            // Creat basic JSON object with data for chart
            var chartData = new
            {
                label = "Example Bar Chart",
                data = new[] {
                    new[] {1,34},
                    new[] {2,24},
                    new[] {3,11},
                    new[] {4,41},
                    new[] {5,17},
                    new[] {6,33}
                }
            };

            // Return JSON object
            return Json(chartData, JsonRequestBehavior.AllowGet);

        }

        public JsonResult tableJsonData()
        {

            // Creat basic JSON object with data for table
            var chartData = new[] {
                    new {Name = "Ashton Cox", Position = "Junior Technical Author", Office = "London", Age = 33},
                    new {Name = "Bradley Greer", Position = "Pre-Sales Support", Office = "Tokyo", Age = 27},
                    new {Name = "Airi Satou", Position = "Integration Specialist", Office = "New York", Age = 43},
                    new {Name = "Caesar Vance", Position = "Software Engineer", Office = "San Francisco", Age = 36},
                };

            // Return JSON object
            return Json(chartData, JsonRequestBehavior.AllowGet);

        }

        public JsonResult calendarEvents()
        {

            // Creat basic JSON object with events for calendar
            var rows = new[] { 
                new { title="Buy milk", start= "2014-12-04" }, 
                new { title="Call to Monica", start= "2014-12-22" }, 
                new { title="Send email to John", start= "2014-12-15" }, 
                new { title="Call to Mark", start= "2014-12-19" }, 
                new { title="Check new product", start= "2014-12-01" } 
            };

            // Return JSON object
            return Json(rows, JsonRequestBehavior.AllowGet);
        }

        public JsonResult tasksJsonData()
        {

            // Creat basic JSON object with data for table
            var tasksData = new[] {
                    new {Type = "Meeting", Time = "2014-12-04", Title = "Meeting with Monica", Desc = "Conference on the sales results for the previous year. Monica please examine sales trends in marketing and products."},
                    new {Type = "Call", Time = "2014-12-18", Title = "Call to Stephen", Desc = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since."},
                    new {Type = "Chat", Time = "2014-12-04", Title = "Chat with Sandra", Desc = "Over the years, sometimes by accident, sometimes on purpose (injected humour and the like). "},
                    new {Type = "File", Time = "2014-12-11", Title = "Send files to Kim", Desc = "Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like). "}
                };

            // Return JSON object
            return Json(tasksData, JsonRequestBehavior.AllowGet);

        }
    }
}

MVC5_Full_Version/Inspinia_MVC5/Views/Json/Index.cshtml
@{
    ViewBag.Title = "JSON Examples";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>JSON Example Page</h2>
        <ol class="breadcrumb">
            <li class="active">
                Basic example how you can use JSON data
            </li>
        </ol>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-6">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Table example</h5>
                </div>
                <div class="ibox-content">
                    <table class="table table-striped" id="ajaxTable">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Position</th>
                                <th>Office</th>
                                <th>Age</th>
                            </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Chart example</h5>
                </div>
                <div class="ibox-content">
                    <div class="flot-chart">
                        <div class="flot-chart-content" id="flot-bar-chart"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-7">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Calendar example</h5>
                </div>
                <div class="ibox-content">
                    <div id="calendar"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-5">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Timeline example</h5>
                </div>
                <div class="ibox-content inspinia-timeline">
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles {
    @Styles.Render("~/plugins/fullCalendarStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/flot")
    @Scripts.Render("~/plugins/fullCalendar")

    <script type="text/javascript">

        // Creat JSON url to controller
        var chartDataUrl = '@Url.Action("flotJsonData", "Json")';
        var tableDataUrl = '@Url.Action("tableJsonData", "Json")';
        var eventsDataUrl = '@Url.Action("calendarEvents", "Json")';
        var tasksDataUrl = '@Url.Action("tasksJsonData", "Json")';

        $(document).ready(function () {

            // Options for bar chart
            var barOptions = {series: {bars: {show: true,barWidth: 0.6,fill: true,fillColor: {colors: [{opacity: 0.8}, {opacity: 0.8}]}}},
                xaxis: {tickDecimals: 0},
                colors: ["#1ab394"],
                grid: {color: "#999999",hoverable: true,clickable: true,tickColor: "#D4D4D4",borderWidth: 0},
                legend: {show: true},
                tooltip: true,
                tooltipOpts: {content: "Item: %x, Value: %y"}
            };

            // Ajax call for chart data
            $.ajax({
                url: chartDataUrl,
                method: 'GET',
                dataType: 'json',
                success: function (data) {
                    $.plot($("#flot-bar-chart"), [data], barOptions);
                }
            });

            // Ajax call for table data
            $.ajax({
                url: tableDataUrl,
                method: 'GET',
                dataType: 'json',
                success: function (data) {
                    var div = $('#ajaxTable');
                    $.each(data, function (i, item) {
                        div.append(
                            $('<tr>')
                                .append($('<td>').html(item.Name)).append($('<td>').html(item.Position)).append($('<td>').html(item.Office)).append($('<td>').html(item.Age))
                            );
                    })
                }
            });

            // Calendar with ajax data
            $('#calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay'
                },
                editable: true,
                // Link to JSON data
                events: eventsDataUrl
            });

            // Ajax call for timeline data
            $.ajax({
                url: tasksDataUrl,
                method: 'GET',
                dataType: 'json',
                success: function (data) {
                    var timelineDiv = $('.inspinia-timeline');
                    $.each(data, function (i, item) {
                        addTimelineTask(timelineDiv, item);
                    })
                }
            });

            // Simple function to append new timeline element
            function addTimelineTask(timelineDiv, task) {
                switch (task.Type) {
                    case 'Call': iconType = "phone";
                        break;
                    case 'Meeting': iconType = "coffee";
                        break;
                    case 'Chat': iconType = "comments";
                        break;
                    case 'File': iconType = "file-text";
                        break;
                    default: iconType = "briefcase";
                }
                timelineDiv.append($('<div class="timeline-item">').html('<div class="row"> <div class="col-xs-3 date"><i class="fa fa-' + iconType + '"></i> ' + task.Time + ' <br></div> <div class="col-xs-7 content"><p class="m-b-xs"><strong>' + task.Title + '</strong></p> <p> ' + task.Desc + '</p> </div> </div>'))
            };
        });
    </script>
}